In [51]:
import numpy as np

In [52]:
x = [2, 4, 6, 2, 9]
y = [3, 5, 9, 4, 7]

In [53]:
mat = np. corrcoef([2, 4, 6, 2, 9], [3, 5, 9, 4, 7])
mat

array([[1.        , 0.77685086],
       [0.77685086, 1.        ]])

In [54]:
import matplotlib.pyplot as plt 

In [55]:
a = np.array([[1, 2, 3], [1, 4, 6]])
b = [1, 2, 2.8]

In [56]:
np.corrcoef(a, b)

array([[1.        , 0.99339927, 0.99794872],
       [0.99339927, 1.        , 0.99870494],
       [0.99794872, 0.99870494, 1.        ]])

In [57]:
np.corrcoef(a)

array([[1.        , 0.99339927],
       [0.99339927, 1.        ]])

In [58]:
random_set = np.random.randn(5)
autre_random_set = np.random.randn(5)
random_set, autre_random_set

(array([-0.257242  ,  0.68129719, -0.61035727,  2.02597851,  0.49747485]),
 array([-0.12159423,  0.39401444, -0.52257607, -0.7333884 ,  1.97992694]))

In [59]:
np.corrcoef(random_set, autre_random_set)

array([[ 1.        , -0.07864028],
       [-0.07864028,  1.        ]])

In [60]:
t = np.random.randint(10, size=5)
t

array([3, 5, 3, 9, 5])

In [61]:
np.corrcoef(np.cos(t), np.sin(t))

array([[ 1.        , -0.97693931],
       [-0.97693931,  1.        ]])

In [62]:
gaussien = np.random.normal(0.5, 1.2, 5)

In [63]:
autre_gaussien = np.random.normal(0.4, 1.1, 5)

In [64]:
np.corrcoef(gaussien, autre_gaussien)

array([[ 1.        , -0.46674359],
       [-0.46674359,  1.        ]])