In [3]:
import numpy as np

In [13]:
nom = ["tata", "toto", "tutu", "titi"]
prenom = ["zaza", "mimi", "lolo", "lilo"]
age = [14, 89, 56, np.random.random()]
fctions = [np.max, np.min, np.median, np.mean]
for ind, (a,b,c,f) in enumerate(zip(nom, prenom, age, fctions)):
    print(ind, " - ", a, " - ", b, " - ", c, " - ", f(age))

0  -  tata  -  zaza  -  14  -  89.0
1  -  toto  -  mimi  -  89  -  0.41588489902591885
2  -  tutu  -  lolo  -  56  -  35.0
3  -  titi  -  lilo  -  0.41588489902591885  -  39.85397122475648


In [25]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
numbers = input("Entrer un nombre")
numbers = numbers.split(",")
pair = []
for number in numbers:
    number = int(number)
    if number%2 == 0:
        pair.append(number)
pair


[50]

In [49]:
sum(range(5), 6)

16

In [53]:
table_2d = np.random.random(size=(8,2))
table_2d

array([[0.18116501, 0.90333378],
       [0.80573435, 0.15292251],
       [0.1110845 , 0.76656295],
       [0.09083483, 0.98597663],
       [0.02297807, 0.24370438],
       [0.91180428, 0.87288164],
       [0.08988937, 0.22679322],
       [0.94981438, 0.43684198]])

In [54]:
table_2d.flatten()

array([0.18116501, 0.90333378, 0.80573435, 0.15292251, 0.1110845 ,
       0.76656295, 0.09083483, 0.98597663, 0.02297807, 0.24370438,
       0.91180428, 0.87288164, 0.08988937, 0.22679322, 0.94981438,
       0.43684198])

In [68]:
calculs = {
    "max": np.max,
    "min": np.min,
    "mean": np.mean
}

In [92]:
a = [4, 8, 6, 7, 0]

In [93]:
a = a>=5
a

TypeError: '>=' not supported between instances of 'list' and 'int'

In [81]:
liste = list(map(lambda x:x*x, a))
liste

[16, 64, 36, 49, 0]

In [111]:
a = 7
b= 0

In [112]:
try:
    division = int(a) / b
    print(division)
except(ZeroDivisionError) as e:
    print(e)
except(ValueError) as e:
    print(e)
except(TypeError) as e:
    print("erreur", e)
finally:
    print('Merci')

division by zero
Merci


In [117]:
x = 5.2
if not type(x) is int:
    raise TypeError("ça n'est pas un entier")

TypeError: ça n'est pas un entier