In [71]:
import numpy as np

In [72]:
nom = ["tata", "toto", "tutu", "titi"]
prenom = ["zaza", "mimi", "lolo", "lilo"]
age = [14, 89, 56, np.random.random()]
fctions = [np.max, np.min, np.median, np.mean]
for ind, (a,b,c,f) in enumerate(zip(nom, prenom, age, fctions)):
    print(ind, " - ", a, " - ", b, " - ", c, " - ", f(age))

0  -  tata  -  zaza  -  14  -  89.0
1  -  toto  -  mimi  -  89  -  0.17800519706165174
2  -  tutu  -  lolo  -  56  -  35.0
3  -  titi  -  lilo  -  0.17800519706165174  -  39.79450129926541


In [73]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [74]:
numbers = input("Entrer un nombre")
numbers = numbers.split(",")
pair = []
for number in numbers:
    number = int(number)
    if number%2 == 0:
        pair.append(number)
pair


[]

In [75]:
sum(range(5), 6)

16

In [76]:
table_2d = np.random.random(size=(8,2))
table_2d

array([[0.54051244, 0.839007  ],
       [0.53795806, 0.56068307],
       [0.31601762, 0.41702281],
       [0.60527014, 0.41261333],
       [0.46076844, 0.92992871],
       [0.26711995, 0.89413721],
       [0.29258524, 0.01587269],
       [0.67836562, 0.86905698]])

In [77]:
table_2d.flatten()

array([0.54051244, 0.839007  , 0.53795806, 0.56068307, 0.31601762,
       0.41702281, 0.60527014, 0.41261333, 0.46076844, 0.92992871,
       0.26711995, 0.89413721, 0.29258524, 0.01587269, 0.67836562,
       0.86905698])

In [78]:
calculs = {
    "max": np.max,
    "min": np.min,
    "mean": np.mean
}

In [79]:
a = [4, 8, 6, 7, 0]

In [80]:
liste = list(map(lambda x:x*x, a))
liste

[16, 64, 36, 49, 0]

In [81]:
a = 7
b= 0

In [82]:
try:
    division = int(a) / b
    print(division)
except(ZeroDivisionError) as e:
    print(e)
except(ValueError) as e:
    print(e)
except(TypeError) as e:
    print("erreur", e)
finally:
    print('Merci')

division by zero
Merci


In [83]:
# x = 5.2
# if not type(x) is int:
#     raise TypeError("ça n'est pas un entier")

In [84]:
import random

In [85]:
def creer_groupe(liste_noms, taille_groupes):
    '''
    Cette fonction prend en entrée une liste de noms, une taille de groupe 
    et classe les noms dans un dictionnaire pour former des groupes de la taille indiquée, si le 
    nombre de personnes n'est pas un multiple de la taille du groupe, les personnes
    restantes forment un dernier groupe plus petit.

    Args:
        liste_noms: liste de noms .
        taille_groupes: taille des groupes souhaitées.

    Returns:
        Dictionnaire contenant les groupes formés.
    '''
    groupes = {}
    numero_groupe = 0
    if len(liste_noms)%taille_groupes == 0:
        nombre_groupes = len(liste_noms)/taille_groupes
        for nombre_groupe in range(nombre_groupes):
            liste_groupe = []
            numero_groupe += 1
            for nom in range(taille_groupes):
                nom_choisi = random.choice(liste_noms)
                indice = -1
                for i, n in enumerate(liste_noms):
                    if n == nom_choisi:
                        indice = i
                liste_groupe.append(nom_choisi)
                liste_noms = np.delete(liste_noms, indice)
            groupes[f"groupe {numero_groupe}"] = liste_groupe
    else:
        nombre_groupes = int(len(liste_noms)/taille_groupes) 
        for nombre_groupe in range(nombre_groupes):
            liste_groupe = []
            numero_groupe += 1
            for nom in range(taille_groupes):
                nom_choisi = random.choice(liste_noms)
                indice = -1
                for i, n in enumerate(liste_noms):
                    if n == nom_choisi:
                        indice = i
                liste_groupe.append(nom_choisi)
                liste_noms = np.delete(liste_noms, indice)
            groupes[f"groupe {numero_groupe}"] = liste_groupe
        liste_groupe = []
        numero_groupe += 1
        for nom in liste_noms:
            liste_groupe.append(nom)
        groupes[f"groupe {numero_groupe}"] = liste_groupe
    return groupes

In [86]:
eleves = [
    "arthur",
    "pierre",
    "marvin",
    "max",
    "charlotte",
    "naïm",
    "abdessamed",
    "fabien",
    "lionel",
    "boris",
    "cédric",
    "jonathan",
    "joachim",
    "mhoudini",
    "ilham",
    "salah",
    "aldrin"
]

In [87]:
creer_groupe(eleves, 9)

{'groupe 1': ['mhoudini',
  'aldrin',
  'salah',
  'marvin',
  'charlotte',
  'ilham',
  'max',
  'cédric',
  'naïm'],
 'groupe 2': ['arthur',
  'pierre',
  'abdessamed',
  'fabien',
  'lionel',
  'boris',
  'jonathan',
  'joachim']}

Numpy random
Faire un générateur de nombre aléatoire pour le loto et l'euromillion. Attention c’est un tirage aléatoire sans remise (c.a.d que la boule trouvée n’est pas remise en jeu) et tous les chiffres ont la même probabilité d’apparaître.

Reprenez l’exercice 16 et faites en sorte que le nombre à trouver soit aléatoire et compris entre 1 et 1000: 
“Écrivez un programme qui demande à l'utilisateur de deviner un nombre secret (par exemple 42). Le programme indique à l'utilisateur si le nombre à deviner est plus grand ou plus petit que sa proposition et continue de demander un nombre tant que l'utilisateur ne trouve pas le nombre secret. Une fois que l'utilisateur trouve le nombre secret, affichez un message de félicitations.”

In [88]:
import numpy as np

In [89]:
def generateur_nombre_loto():
    liste_tirage = {}
    for nb_tirage in range(1, 101):
        nombres_49 = np.array(range(1,50))
        nombre_10 = np.array(range(1, 11))
        liste_nombre = []
        for i in range(5):
            nombre_choisit = np.random.choice(nombres_49)
            liste_nombre.append(nombre_choisit)
            for index, nombre in enumerate(nombres_49):
                if nombre == nombre_choisit:
                    np.delete(nombres_49, index)
        nombre_choisit = np.random.choice(nombre_10)
        liste_nombre.append(nombre_choisit)
        liste_tirage[f"Tirage numéro {nb_tirage}"] = liste_nombre
    return liste_tirage

In [90]:
generateur_nombre_loto()

{'Tirage numéro 1': [13, 49, 7, 30, 13, 2],
 'Tirage numéro 2': [41, 32, 28, 39, 29, 1],
 'Tirage numéro 3': [11, 14, 39, 36, 20, 3],
 'Tirage numéro 4': [20, 43, 1, 49, 25, 8],
 'Tirage numéro 5': [16, 47, 10, 32, 48, 6],
 'Tirage numéro 6': [39, 2, 22, 36, 5, 6],
 'Tirage numéro 7': [10, 12, 8, 14, 48, 7],
 'Tirage numéro 8': [12, 7, 28, 9, 37, 5],
 'Tirage numéro 9': [13, 38, 3, 48, 13, 6],
 'Tirage numéro 10': [23, 14, 37, 16, 46, 4],
 'Tirage numéro 11': [29, 35, 45, 21, 18, 6],
 'Tirage numéro 12': [2, 46, 26, 47, 19, 7],
 'Tirage numéro 13': [36, 46, 4, 48, 1, 8],
 'Tirage numéro 14': [45, 21, 32, 16, 44, 1],
 'Tirage numéro 15': [47, 47, 13, 20, 6, 7],
 'Tirage numéro 16': [30, 6, 34, 5, 33, 9],
 'Tirage numéro 17': [27, 47, 6, 37, 6, 8],
 'Tirage numéro 18': [46, 10, 48, 27, 1, 3],
 'Tirage numéro 19': [40, 47, 16, 34, 3, 6],
 'Tirage numéro 20': [30, 14, 13, 13, 49, 10],
 'Tirage numéro 21': [30, 11, 37, 31, 36, 9],
 'Tirage numéro 22': [26, 34, 40, 5, 40, 3],
 'Tirage numéro

In [91]:
def generateur_nombre_euromillions():
    nombres_49 = np.array(range(1,50))
    nombre_12 = np.array(range(1, 13))
    liste_nombre = []
    for i in range(5):
        nombre_choisit = np.random.choice(nombres_49)
        liste_nombre.append(nombre_choisit)
        for index, nombre in enumerate(nombres_49):
            if nombre == nombre_choisit:
                np.delete(nombres_49, index)
    for i in range(2):
        nombre_choisit = np.random.choice(nombre_12)
        liste_nombre.append(nombre_choisit)
        for index, nombre in enumerate(nombres_49):
            if nombre == nombre_choisit:
                np.delete(nombres_49, index)
    return liste_nombre

In [92]:
generateur_nombre_euromillions()

[44, 47, 39, 28, 40, 10, 1]

In [129]:
def creer_groupe(liste_noms, taille_groupes):
    '''
    Cette fonction prend en entrée une liste de noms, une taille de groupe 
    et classe les noms dans un dictionnaire pour former des groupes de la taille indiquée, si le 
    nombre de personnes n'est pas un multiple de la taille du groupe, les personnes
    restantes forment un dernier groupe plus petit.

    Args:
        liste_noms: liste de noms .
        taille_groupes: taille des groupes souhaitées.

    Returns:
        Dictionnaire contenant les groupes formés.
    '''
    groupes = {}
    numero_groupe = 0
 
    if len(liste_noms)%taille_groupes == 0:
        a = 0
        nombre_groupes = len(liste_noms)/taille_groupes
        np.random.shuffle(liste_noms)
        for nombre_groupe in range(nombre_groupes):
            numero_groupe += 1    
            groupes[f"groupe {numero_groupe}"] =  liste_noms[a:a + taille_groupes]
            a += taille_groupes 
    else:
        a = 0
        nombre_groupes = int(len(liste_noms)/taille_groupes) 
        np.random.shuffle(liste_noms)
        for nombre_groupe in range(nombre_groupes):
            numero_groupe += 1
            groupes[f"groupe {numero_groupe}"] =  liste_noms[a:a + taille_groupes]
            a += taille_groupes
        numero_groupe += 1
        groupes[f"groupe {numero_groupe}"] =  liste_noms[a:]
    return groupes

In [130]:
creer_groupe(eleves, 6)

{'groupe 1': ['boris', 'jonathan', 'lionel', 'aldrin', 'pierre', 'charlotte'],
 'groupe 2': ['cédric', 'fabien', 'mhoudini', 'arthur', 'marvin', 'joachim'],
 'groupe 3': ['ilham', 'naïm', 'max', 'salah', 'abdessamed']}