In [212]:
import numpy as np 

1. Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [213]:
tableau = np.arange(1, 11)
tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1.

In [214]:
alea = np.random.random(5)
alea

array([0.85353216, 0.06490747, 0.46270766, 0.26539031, 0.50436143])

3. Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments.

In [215]:
def somme_tableau(tableau:np.array) -> int:
    return np.sum(tableau)

In [216]:
somme_tableau(tableau=tableau)

55

4. Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [217]:
def produit_scalaire(tableau_1:np.array, tableau_2:np.array) -> int:
    return np.dot(tableau_1, tableau_2)

In [218]:
tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [219]:
alea = np.random.random(10)
alea

array([0.18270396, 0.66589463, 0.65301691, 0.49515096, 0.30197117,
       0.42741288, 0.36549951, 0.17379262, 0.62338126, 0.75456163])

In [220]:
alea.shape, tableau.shape

((10,), (10,))

In [221]:
produit_scalaire(tableau_1=tableau, tableau_2=alea)

26.633366078024586

5. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [222]:
def tableau_unique(tableau:np.array) -> np.array:
    tab = np.unique(tableau, return_counts=True)
    list = []
    for a,b in zip(tab[0], tab[1]):
        if b == 1:
            list.append(a)
    return list    

In [223]:
uni = np.array([1, 5, 6, 7, 5, 6, 1, 0, 12])

In [224]:
tableau_unique(uni)

[0, 7, 12]

6. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.

In [225]:
def classe_tableau(tableau:np.array) -> np.array:
    return np.sort(tableau)

In [226]:
desordre = [5, 8, 2, 1, 10]

In [227]:
classe_tableau(desordre)

array([ 1,  2,  5,  8, 10])

7. Créez une fonction qui prend un tableau NumPy en entrée et renvoie la moyenne, la médiane et l'écart type de ses éléments.

In [228]:
def variable(tableau:np.array) -> np.array:
    return np.mean(tableau), np.median(tableau), np.std(tableau)

In [229]:
variable(desordre)

(5.2, 5.0, 3.4292856398964497)

8. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau où tous les éléments inférieurs à 5 sont remplacés par 0 et tous les éléments supérieurs ou égaux à 5 sont remplacés par 1.

In [230]:
def replace_cinq(tableau:np.array) -> np.array:
    for i, element in enumerate(tableau):
        if element < 5:
            tableau[i] = 0
        else:
            tableau[i] = 1
    return tableau

In [231]:
tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [232]:
replace_cinq(tableau=tableau)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [233]:
def replace_cinq_2(tableau:np.array) -> np.array:
    tableau = tableau >= 5
    tableau = tableau.astype(int)
    return tableau

In [234]:
tab = np.array([5, 9, 2, -4, 5, 3, 8, 10, -7])


In [235]:
replace_cinq_2(tableau=tab)

array([1, 1, 0, 0, 1, 0, 1, 1, 0])

In [241]:
def replace_cinq_3(tableau:np.array) -> np.array:
    return np.where(tableau >= 5, 1, 0)

In [237]:
tab = np.array([5, 9, 2, -4, 5, 3, 8, 10, -7])


In [242]:
replace_cinq_3(tableau=tab)

array([1, 1, 0, 0, 1, 0, 1, 1, 0])

9. Créez un tableau NumPy 2D de taille 3x3 contenant des valeurs entières générées aléatoirement entre 1 et 10.

In [240]:
rand = np.random.randint(1, 11,size=(3,3))
rand

array([[5, 1, 1],
       [5, 6, 2],
       [7, 7, 3]])

In [ ]:
from sklearn.pipeline import Pipeline