In [38]:
import numpy as np

In [39]:
def max(tableau:np.array(float)) -> float: 
    max = tableau[0]
    indice_max = 0
    for indice in range(1, len(tableau)):
        if max < tableau[indice]:
            max = tableau[indice]
            indice_max = indice
    return max, indice_max

In [40]:
def min(tableau:np.array(float)) -> float: 
    min = tableau[0]
    indice_min = 0
    for indice in range(1, len(tableau)):
        if min > tableau[indice]:
            min = tableau[indice]
            indice_min = indice
    return min, indice_min

In [41]:
def classer(tableau, ordre="ascendant"):
    tab_classer = []
    limite = min
    if ordre == "décroissant":
        limite = max
    for nombre in tableau:
        tab_classer.append(limite(tableau=tableau)[0])
        tableau = np.delete(tableau, limite(tableau=tableau)[1])
    return tab_classer    


In [42]:
tab = np.random.random(size=(9))
max(tab)

(0.8309016019938084, 7)

In [43]:
classer(tab, "décroissant")

[0.8309016019938084,
 0.8087209897827545,
 0.7852972533502866,
 0.7119492906893464,
 0.345495197179296,
 0.336334538984996,
 0.3052945919928709,
 0.26853224910019613,
 0.17655153115722022]

In [44]:

np.random.shuffle()

TypeError: RandomState.shuffle() takes exactly one argument (0 given)

In [ ]:
tableau = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [ ]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a + b 

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
A = np.random.randint(1, 11,size=(5,4))
A

array([[2, 8, 8, 7],
       [5, 6, 3, 7],
       [5, 9, 2, 8],
       [5, 8, 7, 2],
       [9, 8, 7, 3]])

In [47]:
A = np.random.randn(4, 4) * 3 + 2
A

array([[ 1.39523058,  5.36755396,  5.52827773,  5.95923361],
       [ 2.34937302,  5.92214671,  0.2328472 ,  3.12783232],
       [-0.18682926,  4.59928691,  5.48695193,  1.3025018 ],
       [ 1.50437151,  0.69336992,  3.47700056,  6.2417156 ]])

In [48]:
Pinv = np.linalg.inv(A)
Pinv

array([[-2.8450565 ,  1.07468329,  1.66043594,  1.83126036],
       [ 0.58503642, -0.07786623, -0.29606416, -0.45775749],
       [-0.84655726,  0.1858741 ,  0.66164002,  0.5770308 ],
       [ 1.09230471, -0.35391186, -0.73587993, -0.55174527]])

In [49]:
Id = np.dot(Pinv, A)
Id

array([[ 1.00000000e+00, -1.40586475e-15,  1.63888651e-15,
        -2.45336823e-16],
       [ 1.78593331e-16,  1.00000000e+00, -7.16819159e-16,
        -1.36049906e-16],
       [-2.46320493e-16, -5.95965012e-16,  1.00000000e+00,
        -1.76309535e-16],
       [ 5.82386915e-16,  1.22510400e-15,  3.41080795e-16,
         1.00000000e+00]])