In [1]:
x ="hello"

In [5]:
def test(listes):
    for liste in listes:
        if (liste):
            print("oui")
        else:
            print("non")

In [6]:
x = ["", "hello"]

In [7]:
test(x)

non
oui


In [8]:
a = (5, 6, 7)

In [9]:
a[0] = 23

TypeError: 'tuple' object does not support item assignment

In [10]:
x = "1"

In [12]:
y = int(x)

In [15]:
type(y), type(x)

(int, str)

In [19]:
import numpy as np
mon_tableau = np.array([[1, 5, 6],
                        [4, 2, 3]])
mon_tableau

array([[1, 5, 6],
       [4, 2, 3]])

In [22]:
mon_tableau.reshape(3, 2)

array([[1, 5],
       [6, 4],
       [2, 3]])

In [24]:
tableau_de_un = np.ones(shape=(5,3))
tableau_de_un

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
# Import PyTorch
import torch
from torch import nn

# Import torchvision 
import torchvision
from torchvision import datasets
from torchvision.transforms import ToTensor

# Import matplotlib for visualization
import matplotlib.pyplot as plt

# Check versions
# Note: your PyTorch version shouldn't be lower than 1.10.0 and torchvision version shouldn't be lower than 0.11
print(f"PyTorch version: {torch.__version__}\ntorchvision version: {torchvision.__version__}")

PyTorch version: 2.0.1+cpu
torchvision version: 0.15.2+cpu


In [38]:
if x=="bonjour" and y=="au_revoir":
    print("oui")

In [36]:
x = "bonjour"
y="salut"

In [49]:
def couple(x):
    return x, x+1

In [40]:
x = np.random.random(size=10)
x

array([0.78992006, 0.78260237, 0.27210068, 0.13568775, 0.72486994,
       0.72403938, 0.4537129 , 0.73220066, 0.83600508, 0.27183664])

In [50]:
y, z = couple(x)
y


array([0.78992006, 0.78260237, 0.27210068, 0.13568775, 0.72486994,
       0.72403938, 0.4537129 , 0.73220066, 0.83600508, 0.27183664])

In [48]:
for k in y:
    print(k)

[0.78992006 0.78260237 0.27210068 0.13568775 0.72486994 0.72403938
 0.4537129  0.73220066 0.83600508 0.27183664]
[1.78992006 1.78260237 1.27210068 1.13568775 1.72486994 1.72403938
 1.4537129  1.73220066 1.83600508 1.27183664]


In [54]:
a = 2 if x==2 else 3
a

3

In [53]:
dico = {"lundi":11,
        "mardi":12,
        "mercredi":13,
        "jeudi":14,
        "vendredi":15}

In [ ]:
[k for k,]